### ISSUE TITLE
TestHiveActionExecutor#testHiveAction fails due to Launcher error

### ISSUE THREAD

**Issue by pravin-dsilva** [OpenPOWER-BigData/HDP-oozie#1]
**Project : sharelib/hive**

The following errors are see on execution of the tests:
`Failed tests:   testHiveAction(org.apache.oozie.action.hadoop.TestHiveActionExecutor): expected:<[SUCCEED]ED> but was:<[FAILED/KILL]ED>`

**Surefire reports org.apache.oozie.action.hadoop.TestHiveActionExecutor-output.txt output:**
`WARN DefaultContainerExecutor:230 - Exception from container-launch with container ID: container_1471599168679_0001_01_000002 and exit code: 1
ExitCodeException exitCode=1:
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:576)
        at org.apache.hadoop.util.Shell.run(Shell.java:487)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:753)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:303)
`

`WARN HiveActionExecutor:523 - USER[test] GROUP[-] TOKEN[] APP[testApp] JOB[0000000-160819093324987-oozie-root-W] ACTION[0000000-160819093324987-oozie-root-W@hive-action] Launcher ERROR, reason: Main class [org.apache.oozie.action.hadoop.HiveMain], exit code [1]
`

**target/MiniMRCluster_  stderr output:**

```
Query ID = root_20160819093433_f24b7414-6748-4e54-8498-632c5df2dd1d
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks is set to 0 since there's no reduce operator
Halting due to Out Of Memory Error..

```

**Comment by pravin-dsilva** [comment]
The issue is resolved by setting _JAVA_OPTIONS environment variable

`export _JAVA_OPTIONS="-XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:MaxPermSize=1024m"`
